// Redux/PaperSet/actionTypes.js
export const CREATE_SET_REQUEST = "CREATE_SET_REQUEST";
export const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
export const CREATE_SET_FAIL = "CREATE_SET_FAIL";

export const FETCH_SETS_REQUEST = "FETCH_SETS_REQUEST";
export const FETCH_SETS_SUCCESS = "FETCH_SETS_SUCCESS";
export const FETCH_SETS_FAIL = "FETCH_SETS_FAIL";

export const GET_SET_REQUEST = "GET_SET_REQUEST";
export const GET_SET_SUCCESS = "GET_SET_SUCCESS";
export const GET_SET_FAIL = "GET_SET_FAIL";

export const UPDATE_SET_REQUEST = "UPDATE_SET_REQUEST";
export const UPDATE_SET_SUCCESS = "UPDATE_SET_SUCCESS";
export const UPDATE_SET_FAIL = "UPDATE_SET_FAIL";

export const DELETE_SET_REQUEST = "DELETE_SET_REQUEST";
export const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";
export const DELETE_SET_FAIL = "DELETE_SET_FAIL";

export const ADD_QUESTIONS_TO_SET_REQUEST = "ADD_QUESTIONS_TO_SET_REQUEST";
export const ADD_QUESTIONS_TO_SET_SUCCESS = "ADD_QUESTIONS_TO_SET_SUCCESS";
export const ADD_QUESTIONS_TO_SET_FAIL = "ADD_QUESTIONS_TO_SET_FAIL";

export const REMOVE_QUESTION_FROM_SET_REQUEST = "REMOVE_QUESTION_FROM_SET_REQUEST";
export const REMOVE_QUESTION_FROM_SET_SUCCESS = "REMOVE_QUESTION_FROM_SET_SUCCESS";
export const REMOVE_QUESTION_FROM_SET_FAIL = "REMOVE_QUESTION_FROM_SET_FAIL";
