export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST"
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS"
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL"

export const FETCH_QUESTION_REQUEST = "FETCH_QUESTION_REQUEST"
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS"
export const FETCH_QUESTION_FAIL = "FETCH_QUESTION_FAIL"

export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAIL    = "GET_QUESTION_FAIL";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAIL    = "UPDATE_QUESTION_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL    = "DELETE_QUESTION_FAIL";