// CREATE
export const CREATE_DOMAIN_REQUEST = "CREATE_DOMAIN_REQUEST";
export const CREATE_DOMAIN_SUCCESS = "CREATE_DOMAIN_SUCCESS";
export const CREATE_DOMAIN_FAIL = "CREATE_DOMAIN_FAIL";

// FETCH ALL
export const FETCH_DOMAINS_REQUEST = "FETCH_DOMAINS_REQUEST";
export const FETCH_DOMAINS_SUCCESS = "FETCH_DOMAINS_SUCCESS";
export const FETCH_DOMAINS_FAIL = "FETCH_DOMAINS_FAIL";

// GET BY ID
export const GET_DOMAIN_REQUEST = "GET_DOMAIN_REQUEST";
export const GET_DOMAIN_SUCCESS = "GET_DOMAIN_SUCCESS";
export const GET_DOMAIN_FAIL = "GET_DOMAIN_FAIL";

// UPDATE
export const UPDATE_DOMAIN_REQUEST = "UPDATE_DOMAIN_REQUEST";
export const UPDATE_DOMAIN_SUCCESS = "UPDATE_DOMAIN_SUCCESS";
export const UPDATE_DOMAIN_FAIL = "UPDATE_DOMAIN_FAIL";

// DELETE
export const DELETE_DOMAIN_REQUEST = "DELETE_DOMAIN_REQUEST";
export const DELETE_DOMAIN_SUCCESS = "DELETE_DOMAIN_SUCCESS";
export const DELETE_DOMAIN_FAIL = "DELETE_DOMAIN_FAIL";
