export const DOMAIN_DATA = [
  // ================= Technical =================
  { category: "Technical", domain: "Cyber security", description: "Protect systems, apps, and networks from attacks and vulnerabilities." },
  { category: "Technical", domain: "App Development", description: "Design and build mobile apps for Android and iOS." },
  { category: "Technical", domain: "Data Engineering", description: "Build data pipelines, ETL, and warehouses for analytics." },
  { category: "Technical", domain: "Game Development", description: "Create interactive games using engines like Unity/Unreal." },
  { category: "Technical", domain: "Dot Net Development", description: "Develop apps with C# and the .NET platform." },
  { category: "Technical", domain: "Business Analyst", description: "Translate business needs into clear, testable tech requirements." },
  { category: "Technical", domain: "Software Testing", description: "Plan and execute tests to ensure software quality." },
  { category: "Technical", domain: "Java Full Stack Development", description: "Build frontend UIs and backend APIs using Java/Spring." },
  { category: "Technical", domain: "Python Development", description: "Develop backend services, scripts, and automations in Python." },
  { category: "Technical", domain: "React Development", description: "Build modern SPA frontends using React.js." },
  { category: "Technical", domain: "Video Editing", description: "Edit and produce videos for marketing and education." },
  { category: "Technical", domain: "Graphic Design", description: "Create logos, banners, and visual layouts." },
  { category: "Technical", domain: "UI/UX Design", description: "Design user-centered interfaces and experiences." },
  { category: "Technical", domain: "Digital Marketing", description: "Grow traffic and conversions via SEO, content, and ads." },
  { category: "Technical", domain: "Advance Excel", description: "Use advanced Excel features for reporting and analysis." },
  { category: "Technical", domain: "Flutter Development", description: "Build cross-platform mobile apps with Flutter/Dart." },
  { category: "Technical", domain: "Data Visualization(Power BI)", description: "Create dashboards and reports with Power BI." },
  { category: "Technical", domain: "Data Science", description: "Analyze data and build models to derive insights." },
  { category: "Technical", domain: "MEAN Stack Development", description: "Develop apps with MongoDB, Express, Angular, and Node." },
  { category: "Technical", domain: "MERN Stack Development", description: "Develop apps with MongoDB, Express, React, and Node." },
  { category: "Technical", domain: "Machine Learning", description: "Build predictive models using ML algorithms." },
  { category: "Technical", domain: "Artificial Intelligence", description: "Apply AI techniques for intelligent automation." },
  { category: "Technical", domain: "Data Analytics", description: "Explore and interpret data to support decisions." },
  { category: "Technical", domain: "Web Development", description: "Create responsive websites using modern web stacks." },
  { category: "Technical", domain: "WordPress Development", description: "Build and customize websites using WordPress." },
  { category: "Technical", domain: "Python Full Stack Development", description: "Frontend and backend development with Python frameworks." },
  { category: "Technical", domain: "Full Stack Development", description: "End-to-end web app development across frontend and backend." },
  { category: "Technical", domain: "SEO", description: "Optimize websites to rank higher on search engines." },
  { category: "Technical", domain: "Frontend Development", description: "Implement user interfaces with HTML, CSS, and JavaScript." },
  { category: "Technical", domain: "Backend Development", description: "Build server APIs, business logic, and integrations." },
  { category: "Technical", domain: "MS SQL", description: "Design and manage databases with Microsoft SQL Server." },

  // ================= Non-Technical =================
  { category: "Non-Technical", domain: "Project Management", description: "Plan, execute, and deliver projects on time and budget." },
  { category: "Non-Technical", domain: "Sales Executive", description: "Drive revenue through lead generation and deal closing." },
  { category: "Non-Technical", domain: "Social Media Handling", description: "Operate brand profiles and daily social interactions." },
  { category: "Non-Technical", domain: "Social Media Management", description: "Plan calendars and track performance across platforms." },
  { category: "Non-Technical", domain: "Social Media Marketing", description: "Run campaigns to grow reach, engagement, and leads." },
  { category: "Non-Technical", domain: "Accounting", description: "Manage bookkeeping, invoices, and financial records." },
  { category: "Non-Technical", domain: "Content Creation", description: "Produce blogs, videos, and creatives for audiences." },
  { category: "Non-Technical", domain: "BDE ( Business Development Executive )", description: "Prospect and develop new business opportunities." },
  { category: "Non-Technical", domain: "HR", description: "Recruitment, onboarding, and employee relations." },
  { category: "Non-Technical", domain: "Content Writing", description: "Write clear, SEO-friendly copy and articles." },
  { category: "Non-Technical", domain: "Email Marketing", description: "Create and optimize email campaigns and automations." },
  { category: "Non-Technical", domain: "Tele Calling", description: "Contact leads and customers via phone for outreach." },
  { category: "Non-Technical", domain: "Support Calling", description: "Assist customers and resolve issues over calls." },
  { category: "Non-Technical", domain: "Meta & Google ads.", description: "Plan and manage paid ads on Meta and Google." },
  { category: "Non-Technical", domain: "BDA( Business Development Associate )", description: "Qualify leads and support the sales pipeline." }
];
