// src/redux/result/result.actionTypes.js

export const GET_RESULTS_BY_IDENTITY_REQUEST = "GET_RESULTS_BY_IDENTITY_REQUEST";
export const GET_RESULTS_BY_IDENTITY_SUCCESS = "GET_RESULTS_BY_IDENTITY_SUCCESS";
export const GET_RESULTS_BY_IDENTITY_FAILURE = "GET_RESULTS_BY_IDENTITY_FAILURE";

export const GET_RESULT_BY_EXAMID_REQUEST = "GET_RESULT_BY_EXAMID_REQUEST";
export const GET_RESULT_BY_EXAMID_SUCCESS = "GET_RESULT_BY_EXAMID_SUCCESS";
export const GET_RESULT_BY_EXAMID_FAILURE = "GET_RESULT_BY_EXAMID_FAILURE";
