// action type constants
export const EMP_CREATE_REQUEST = "EMP_CREATE_REQUEST";
export const EMP_CREATE_SUCCESS = "EMP_CREATE_SUCCESS";
export const EMP_CREATE_FAIL = "EMP_CREATE_FAIL";

export const EMP_RESEND_REQUEST = "EMP_RESEND_REQUEST";
export const EMP_RESEND_SUCCESS = "EMP_RESEND_SUCCESS";
export const EMP_RESEND_FAIL = "EMP_RESEND_FAIL";

export const EMP_LIST_REQUEST = "EMP_LIST_REQUEST";
export const EMP_LIST_SUCCESS = "EMP_LIST_SUCCESS";
export const EMP_LIST_FAIL = "EMP_LIST_FAIL";

export const EMP_CLEAR_ERRORS = "EMP_CLEAR_ERRORS";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERRORS = "AUTH_CLEAR_ERRORS";

