// redux/evaluationActionTypes.js

export const EVALUATE_EXAM_REQUEST = "EVALUATE_EXAM_REQUEST";
export const EVALUATE_EXAM_SUCCESS = "EVALUATE_EXAM_SUCCESS";
export const EVALUATE_EXAM_FAILURE = "EVALUATE_EXAM_FAILURE";

export const FETCH_EVALUATION_HISTORY_REQUEST = "FETCH_EVALUATION_HISTORY_REQUEST";
export const FETCH_EVALUATION_HISTORY_SUCCESS = "FETCH_EVALUATION_HISTORY_SUCCESS";
export const FETCH_EVALUATION_HISTORY_FAILURE = "FETCH_EVALUATION_HISTORY_FAILURE";
