// Redux/Paper/actionType.js

// CREATE
export const CREATE_PAPER_REQUEST = "CREATE_PAPER_REQUEST";
export const CREATE_PAPER_SUCCESS = "CREATE_PAPER_SUCCESS";
export const CREATE_PAPER_FAIL = "CREATE_PAPER_FAIL";

// UPDATE
export const UPDATE_PAPER_REQUEST = "UPDATE_PAPER_REQUEST";
export const UPDATE_PAPER_SUCCESS = "UPDATE_PAPER_SUCCESS";
export const UPDATE_PAPER_FAIL = "UPDATE_PAPER_FAIL";

// DELETE
export const DELETE_PAPER_REQUEST = "DELETE_PAPER_REQUEST";
export const DELETE_PAPER_SUCCESS = "DELETE_PAPER_SUCCESS";
export const DELETE_PAPER_FAIL = "DELETE_PAPER_FAIL";

// FETCH ALL
export const FETCH_PAPER_REQUEST = "FETCH_PAPER_REQUEST";
export const FETCH_PAPER_SUCCESS = "FETCH_PAPER_SUCCESS";
export const FETCH_PAPER_FAIL = "FETCH_PAPER_FAIL";
